<?php
/**
 * About Us Section with a light transition background
 */
return array(
	'title'      => __( 'Leores FAQ (Zentriert)', 'leores' ),
	'categories' => array( 'leorestheme' ),
    'content' => '<!-- wp:group -->
    <div class="wp-block-group"><!-- wp:group {"layout":{"inherit":false,"contentSize":"480px"}} -->
    <div class="wp-block-group"><!-- wp:heading {"textAlign":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"200","lineHeight":"1.2"}},"textColor":"black","className":"lr-faq-title","fontSize":"x-large","fontFamily":"jost"} -->
    <h2 class="has-text-align-center lr-faq-title has-black-color has-text-color has-jost-font-family has-x-large-font-size" style="font-style:normal;font-weight:200;line-height:1.2">Häufig gestellte Fragen und Antworten</h2>
    <!-- /wp:heading -->
    
    <!-- wp:spacer {"height":"10px"} -->
    <div style="height:10px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer --></div>
    <!-- /wp:group -->
    
    <!-- wp:group {"layout":{"contentSize":"600px"}} -->
    <div class="wp-block-group"><!-- wp:spacer {"height":"1px"} -->
    <div style="height:1px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    
    <!-- wp:rank-math/faq-block {"titleWrapper":"p","questions":[{"id":"faq-question-1659713209221","title":"\u003cstrong\u003eIst der individuelle Vermögensplan und die dazugehörige Beratung vom Experten wirklich kostenfrei?\u003c/strong\u003e","content":"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.","visible":true},{"id":"faq-question-1659713227104","title":"\u003cstrong\u003eIst ein ein kostenfreies Gespräch mit einem Experten hierfür zwingend notwendig?\u003c/strong\u003e","content":"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.","visible":true},{"id":"faq-question-1659713240768","title":"\u003cstrong\u003eIst der individuelle Vermögensplan und die dazugehörige Beratung vom Experten wirklich kostenfrei?\u003c/strong\u003e","content":"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.","visible":true},{"id":"faq-question-1659713248751","title":"\u003cstrong\u003eWie schnell erhalte ich den Plan und die Beratung und wie lange dauert es, bis ich mein Vermögen schützen kann?\u003c/strong\u003e","content":"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.","visible":true}]} -->
    <div class="wp-block-rank-math-faq-block"><div class="rank-math-faq-item"><p class="rank-math-question"><strong>Ist der individuelle Vermögensplan und die dazugehörige Beratung vom Experten wirklich kostenfrei?</strong></p><div class="rank-math-answer">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</div></div><div class="rank-math-faq-item"><p class="rank-math-question"><strong>Ist ein ein kostenfreies Gespräch mit einem Experten hierfür zwingend notwendig?</strong></p><div class="rank-math-answer">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</div></div><div class="rank-math-faq-item"><p class="rank-math-question"><strong>Ist der individuelle Vermögensplan und die dazugehörige Beratung vom Experten wirklich kostenfrei?</strong></p><div class="rank-math-answer">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</div></div><div class="rank-math-faq-item"><p class="rank-math-question"><strong>Wie schnell erhalte ich den Plan und die Beratung und wie lange dauert es, bis ich mein Vermögen schützen kann?</strong></p><div class="rank-math-answer">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</div></div></div>
    <!-- /wp:rank-math/faq-block --></div>
    <!-- /wp:group --></div>
    <!-- /wp:group -->'
);